# .github/workflows/generate-meta.yml
name: Generate Meta File
on:
  push:
    paths: [ '*.user.js' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract header
        run: |
          sed -n '/^\/\/ ==UserScript==/,/^\/\/ ==\/UserScript==/p' bili-msg-bg.user.js > bili-msg-bg.meta.js
      - name: Commit meta
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add bili-msg-bg.meta.js
          git commit -m "chore: update meta file(p≧w≦q)" || exit 0
          git push
